language: python
python: 2.7
cache: pip
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - ACTION=loadtest
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
