language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - ACTION=loadtest
install:
    - if [[ $ACTION != loadtest ]]; then pip install tox; fi
    - if [[ $ACTION == loadtest ]]; then pip install psycopg2; fi
script:
    - if [[ $ACTION != loadtest ]]; then tox -e $TOX_ENV; fi
    - if [[ $ACTION == loadtest ]]; then make loadtest-check; fi
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
