dist: bionic
language: python
python: 2.7
cache: pip
env:
  - TOX_ENV=py27
  - TOX_ENV=flake8
  - TOX_ENV=docs
install:
  - pip install tox
script: tox -e $TOX_ENV
after_success:
  - pip install coveralls
  - coveralls

matrix:
  include:
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.7
      env:
        - TOX_ENV=py37
    - python: 3.8
      env:
        - TOX_ENV=py38
    - python: 3.8
      env:
        - TOX_ENV=flake8
